### ISSUE TITLE
0.3.0 False positive warning for persistent script variable declaration 

### ISSUE THREAD

**Issue by skk50** [Orvid/Caprica#28]
Caprica Papyrus Compiler v0.3.0
Compiling SKK_ShipToolsQuestScript.psc
SKK_ShipToolsQuestScript.psc (8, 7:21): Warning W4007: The script variable 'fScriptVersion' is initialized but is never used.

;*******************************************
Scriptname SKK_ShipToolsQuestScript extends Quest

Float fScriptVersion = 0.0

Event OnQuestInit()
   fScriptVersion = 1.0 ;this would beg to differ
EndEvent
;*******************************************

**Comment by nikitalita** [comment]
this would be the correct output for this particular script. While the variable is written to, it's never read, and as such the value is never used. Since object variables can't be inherited by child objects and can't be accessed by external objects like properties can, this will remain only written and not read from. Thus, we consider it unused.

**Comment by skk50** [comment]
Welp adding this clears the condition:

Debug.Trace("SKK_ShipToolsQuestScript.OnQuestInit " + fScriptversion, aiSeverity=0) 

Which is just odd. But your compiler, your rules.
